In [1]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/User/Desktop/cdac advance modules/pml lecture/class  practice/program_dataset/Housing.csv")

In [10]:
df=pd.get_dummies(df,drop_first=True)
df

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,1,0,1,0,0,0
1,38500.0,4000,2,1,1,0,1,0,0,0,0,0
2,49500.0,3060,3,1,1,0,1,0,0,0,0,0
3,60500.0,6650,3,1,2,0,1,1,0,0,0,0
4,61000.0,6360,2,1,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,1,1,0,0,1,0
542,94000.0,6000,3,2,4,0,1,0,0,0,1,0
543,103000.0,6000,3,2,4,1,1,1,0,0,1,0
544,105000.0,6000,3,2,2,1,1,1,0,0,1,0
545,105000.0,6000,3,1,2,1,1,0,0,0,1,0

In [11]:
X = df.iloc[:,1:]
y = df.iloc[:,1]

In [12]:
knnr = KNeighborsRegressor() 
dtr = DecisionTreeRegressor()

In [15]:
for clf in(knnr,dtr):
    if clf==knnr:
        parameters = {'n_neighbors': np.arange(1,16)}
        kfold = KFold(n_splits=5 , random_state=42,shuffle=True)
        cv = GridSearchCV(knnr, param_grid=parameters,
                  cv=kfold,scoring='r2',verbose=0)
        cv.fit( X , y )
        print(clf.__class__.__name__,cv.best_params_)
        print(clf.__class__.__name__,cv.best_score_)

    elif clf==dtr:
        depth_range = [3,4,5,6,7,8,9]
        minsplit_range = [5,10,20,25,30]
        minleaf_range = [5,10,15]

        parameters = dict(max_depth=depth_range,
                  min_samples_split=minsplit_range, 
                  min_samples_leaf=minleaf_range)

        from sklearn.model_selection import KFold
        kfold = KFold(n_splits=5, random_state=2021,shuffle=True)
        from sklearn.model_selection import GridSearchCV
        clf = DecisionTreeRegressor(random_state=2021)
        cv = GridSearchCV(clf, param_grid=parameters,
                  cv=kfold,scoring='r2')

        cv.fit( X , y )
        print(clf.__class__.__name__,cv.best_params_)
        print(clf.__class__.__name__,cv.best_score_)

KNeighborsRegressor {'n_neighbors': 1}
KNeighborsRegressor 0.9952638212948945
DecisionTreeRegressor {'max_depth': 9, 'min_samples_leaf': 5, 'min_samples_split': 5}
DecisionTreeRegressor 0.9906910771663224